### ISSUE TITLE
1. XPR should be XRP  2. Product pricing should remain in dollars

### ISSUE THREAD

**Issue by ciouz** [caspermekel/woocommerce-ripple-gateway#1]
1. The label of the currency is a typo.

2. Product pricing looks strange with (# XRP) next to dollar amount. I think there should be an option to disable this. Also on the checkout page the (# XRP) should be disabled if you add this feature in. The only place I'd like to see the amount of XRP is when I click on "Ripple XRP Payment" option on the checkout page, the way you have it displaying the conversion and total is good. 

I have the current version installed on chainstoreleads.com - feel free to take a look.

**Comment by caspermekel** [comment]
1. Will fix that with next release
2. Try 'show prices in xrp' in settings :)

I will try to add another source for exchange rate, looking for one that supports more than just USD and EUR

**Comment by ciouz** [comment]
Cool :)

https://xrpcharts.ripple.com/#/ shows a few sources they use for CNY and JPY conversions.
